---
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
  - php: 5.4
    env:
    - SYMFONY_VERSION="2.3.*"
    - PHPUNIT=phpunit-5.7
    - TEST_LINT=`true`
    - PHP_CS_FIXER=`true`
    - SENSIO_SECURITY=`true`
  - php: 5.4
    env:
    - SYMFONY_VERSION="2.7.*"
    - PHPUNIT=phpunit-5.7
    - TEST_LINT=`true`
    - PHP_CS_FIXER=`true`
    - SENSIO_SECURITY=`true`
  - php: 5.4
    env:
    - SYMFONY_LTS="2"
    - PHPUNIT=phpunit-4.8
    - TEST_LINT=`true`
    - PHP_CS_FIXER=`true`
    - SENSIO_SECURITY=`true`
  - php: 5.4
    env:
    - SYMFONY_LTS="3"
    - PHPUNIT=phpunit-5.7
    - TEST_LINT=`true`
    - PHP_CS_FIXER=`true`
    - SENSIO_SECURITY=`true`
  - php: 7.2
    env:
    - SYMFONY_LTS="3"
    - PHPUNIT=phpunit
    - TEST_LINT=`true`
    - PHP_CS_FIXER=`true`
    - SENSIO_SECURITY=`true`

before_install:
- source /etc/os-release ; echo $VERSION
- echo $PHPUNIT
- pwd
- echo $HOME
- echo $TRAVIS_PHP_VERSION
- which composer
- ls /tmp
- php --ini
- xdebug=/home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini
- if [[ -f $xdebug ]]; then cat $xdebug; cp $xdebug /tmp; phpenv config-rm xdebug.ini; fi
- xdebug_php=
- if [[ -f /tmp/xdebug.ini ]]; then xdebug_php='-c /tmp/xdebug.ini'; fi
- install --directory .travis/bin
- if [[ -v PHP_CS_FIXER ]]; then wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar --output-document=.travis/bin/php-cs-fixer; fi
- if [[ -v PHPUNIT ]]; then wget https://phar.phpunit.de/${PHPUNIT}.phar --output-document=.travis/bin/$PHPUNIT; fi
- if [[ -v SENSIO_SECURITY ]]; then wget http://get.sensiolabs.org/security-checker.phar --output-document=.travis/bin/security-checker; fi

install:
  - composer validate
  - if [[ -v SYMFONY_VERSION ]]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-scripts --no-progress --no-suggest; fi
  - if [[ -v SYMFONY_LTS ]]; then composer require symfony/lts:${SYMFONY_LTS} --no-scripts --no-progress --no-suggest; fi
  # - composer install --no-scripts --no-progress --no-suggest
  - if [[ -f config/parameters.yml.travis ]]; then cp config/parameters.yml.travis config/parameters.yml; fi
  - composer install --no-progress --no-suggest --optimize-autoloader --apcu-autoloader
  - composer show

before_script:

script:
  - for f in $(find . -path './vendor' -prune -o -path './tests' -prune -o -name \*.php '!' -name VariadicController.php -print) ; do php -l $f ; done # Do this first!
  - if [[ "5.5" < "$TRAVIS_PHP_VERSION" ]]; then php -l VariadicController.php; fi
  - if [[ -v TEST_LINT ]]; then for f in $(find ./tests -name \*.php -print); do php -l $f; done; fi
  - if [[ -v PHP_CS_FIXER ]]; then php .travis/bin/php-cs-fixer --version; fi
  - if [[ -v PHP_CS_FIXER ]]; then php .travis/bin/php-cs-fixer fix --stop-on-violation --diff --dry-run -vvv --using-cache=no; fi

  - if [[ "5.5" < "$TRAVIS_PHP_VERSION" ]]; then PHPUNIT_COVERAGE="--coverage-text --coverage-clover /tmp/coverage.xml"; fi
  - if [[ -v PHPUNIT ]]; then php --ini -c /tmp/xdebug.ini; php $xdebug_php .travis/bin/$PHPUNIT --colors=always $PHPUNIT_COVERAGE; fi
  
  - if [[ -v SENSIO_SECURITY ]]; then php .travis/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock; fi
    #^ This checks that the application doesn't use dependencies with known security vulnerabilities
  - if [[ -v VENDOR_LINT ]]; then for f in $(find ./vendor -name \*.php); do php -l $f > /dev/null; done; fi
    #^ Should be the last line of install but sometimes long to execute and little can be done for errors found.

after_success:
    - if [[ "5.5" < "$TRAVIS_PHP_VERSION" ]] && [[ "7.3" > "$TRAVIS_PHP_VERSION" ]]; then bash <(curl -s https://codecov.io/bash) -s /tmp; fi

# inspirated from:
  # symfony/symfony-demo
  # https://github.com/doctrine/dbal/blob/v2.5.13/.travis.yml
